During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.6/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1046, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 984, in send
    self.connect()
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connection.py", line 187, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connection.py", line 172, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f42202f4be0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 727, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.6/dist-packages/urllib3/util/retry.py", line 446, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='rfxsolution_rfxplatform-api_1', port=8809): Max retries exceeded with url: /rfx/license/tradingparams (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f42202f4be0>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/rfxapp/license-pub.py", line 46, in <module>
    requests.put(url=f"{url}", json=data)
  File "/usr/local/lib/python3.6/dist-packages/requests/api.py", line 131, in put
    return request('put', url, data=data, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='rfxsolution_rfxplatform-api_1', port=8809): Max retries exceeded with url: /rfx/license/tradingparams (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f42202f4be0>: Failed to establish a new connection: [Errno 111] Connection refused',))
Jan 20 12:14:38 0f165c86e48d appd[26]: endpoint_fxsupplier: error Traceback (most recent call last):
Jan 20 12:14:38 0f165c86e48d appd[26]: endpoint_fxsupplier: error File "/rfxapp/bin/endpoint-fxsupplier.py", line 209, in <module>
Jan 20 12:14:38 0f165c86e48d appd[26]: endpoint_fxsupplier: error main()
Jan 20 12:14:38 0f165c86e48d appd[26]: endpoint_fxsupplier: error File "/rfxapp/bin/endpoint-fxsupplier.py", line 192, in main
Jan 20 12:14:38 0f165c86e48d appd[26]: endpoint_fxsupplier: error apply_markup_fxspot = license_fxsupplier_apply_markup_fxspot_get()
Jan 20 12:14:38 0f165c86e48d appd[26]: endpoint_fxsupplier: error File "/opt/robotfx/lib/liblicense.py", line 37, in license_fxsupplier_apply_markup_fxspot_get
Jan 20 12:14:38 0f165c86e48d appd[26]: endpoint_fxsupplier: error pf = license_product_feature_get()
Jan 20 12:14:38 0f165c86e48d appd[26]: endpoint_fxsupplier: error File "/opt/robotfx/lib/liblicense.py", line 31, in license_product_feature_get
Jan 20 12:14:38 0f165c86e48d appd[26]: endpoint_fxsupplier: error return data[LICENSE_PRODUCT_FEATURE]
Jan 20 12:14:38 0f165c86e48d appd[26]: endpoint_fxsupplier: error TypeError: 'int' object is not subscriptable
Jan 20 12:14:38 0f165c86e48d appd[26]: service endpoint_fxsupplier finished code 1 status 0
Jan 20 12:14:38 0f165c86e48d appd[26]: service endpoint_fxsupplier scheduled for restart in 3 seconds, timerid 201326593
Jan 20 12:14:41 0f165c86e48d appd[26]: service endpoint_fxsupplier restarted on error, timerid 201326593
Jan 20 12:14:41 0f165c86e48d appd[26]: service endpoint_fxsupplier started
Jan 20 12:14:41 0f165c86e48d appd[26]: endpoint_fxsupplier: info b'apply_markup_fxspot: 1'
Jan 20 12:14:41 0f165c86e48d appd[26]: endpoint_fxsupplier: info b'apply_markup_fxndf: 1'
Jan 20 12:15:33 0f165c86e48d appd[26]: endpoint_spot: error [DEBUG] - [2022-01-20 12:15:33,144] - amqpstorm.channel0 - Frame Received: Heartbeat
Jan 20 12:15:33 0f165c86e48d appd[26]: endpoint_ndf: error [DEBUG] - [2022-01-20 12:15:33,455] - amqpstorm.channel0 - Frame Received: Heartbeat
Jan 20 12:16:33 0f165c86e48d appd[26]: endpoint_spot: error [DEBUG] - [2022-01-20 12:16:33,146] - amqpstorm.channel0 - Frame Received: Heartbeat
Jan 20 12:16:33 0f165c86e48d appd[26]: endpoint_spot: error [DEBUG] - [2022-01-20 12:16:33,152] - amqpstorm.channel0 - Frame Sent: Heartbeat
Jan 20 12:16:33 0f165c86e48d appd[26]: endpoint_ndf: error [DEBUG] - [2022-01-20 12:16:33,457] - amqpstorm.channel0 - Frame Received: Heartbeat
Jan 20 12:16:33 0f165c86e48d appd[26]: endpoint_ndf: error [DEBUG] - [2022-01-20 12:16:33,461] - amqpstorm.channel0 - Frame Sent: Heartbeat
Jan 20 12:17:33 0f165c86e48d appd[26]: endpoint_spot: error [DEBUG] - [2022-01-20 12:17:33,148] - amqpstorm.channel0 - Frame Received: Heartbeat
Jan 20 12:17:33 0f165c86e48d appd[26]: endpoint_spot: error [DEBUG] - [2022-01-20 12:17:33,152] - amqpstorm.channel0 - Frame Sent: Heartbeat
Jan 20 12:17:33 0f165c86e48d appd[26]: endpoint_ndf: error [DEBUG] - [2022-01-20 12:17:33,459] - amqpstorm.channel0 - Frame Received: Heartbeat
Jan 20 12:17:33 0f165c86e48d appd[26]: endpoint_ndf: error [DEBUG] - [2022-01-20 12:17:33,461] - amqpstorm.channel0 - Frame Sent: Heartbeat
Jan 20 12:18:33 0f165c86e48d appd[26]: endpoint_spot: error [DEBUG] - [2022-01-20 12:18:33,150] - amqpstorm.channel0 - Frame Received: Heartbeat
Jan 20 12:18:33 0f165c86e48d appd[26]: endpoint_spot: error [DEBUG] - [2022-01-20 12:18:33,153] - amqpstorm.channel0 - Frame Sent: Heartbeat
Jan 20 12:18:33 0f165c86e48d appd[26]: endpoint_ndf: error [DEBUG] - [2022-01-20 12:18:33,461] - amqpstorm.channel0 - Frame Received: Heartbeat
Jan 20 12:18:33 0f165c86e48d appd[26]: endpoint_ndf: error [DEBUG] - [2022-01-20 12:18:33,462] - amqpstorm.channel0 - Frame Sent: Heartbeat
Jan 20 12:19:33 0f165c86e48d appd[26]: endpoint_spot: error [DEBUG] - [2022-01-20 12:19:33,152] - amqpstorm.channel0 - Frame Received: Heartbeat
Jan 20 12:19:33 0f165c86e48d appd[26]: endpoint_spot: error [DEBUG] - [2022-01-20 12:19:33,153] - amqpstorm.channel0 - Frame Sent: Heartbeat
Jan 20 12:19:33 0f165c86e48d appd[26]: endpoint_ndf: error [DEBUG] - [2022-01-20 12:19:33,462] - amqpstorm.channel0 - Frame Sent: Heartbeat
Jan 20 12:19:33 0f165c86e48d appd[26]: endpoint_ndf: error [DEBUG] - [2022-01-20 12:19:33,463] - amqpstorm.channel0 - Frame Received: Heartbeat
Jan 20 12:20:33 0f165c86e48d appd[26]: endpoint_spot: error [DEBUG] - [2022-01-20 12:20:33,153] - amqpstorm.channel0 - Frame Sent: Heartbeat
Jan 20 12:20:33 0f165c86e48d appd[26]: endpoint_spot: error [DEBUG] - [2022-01-20 12:20:33,154] - amqpstorm.channel0 - Frame Received: Heartbeat
Jan 20 12:20:33 0f165c86e48d appd[26]: endpoint_ndf: error [DEBUG] - [2022-01-20 12:20:33,463] - amqpstorm.channel0 - Frame Sent: Heartbeat
Jan 20 12:20:33 0f165c86e48d appd[26]: endpoint_ndf: error [DEBUG] - [2022-01-20 12:20:33,465] - amqpstorm.channel0 - Frame Received: Heartbeat
Jan 20 12:21:33 0f165c86e48d appd[26]: endpoint_spot: error [DEBUG] - [2022-01-20 12:21:33,154] - amqpstorm.channel0 - Frame Sent: Heartbeat
Jan 20 12:21:33 0f165c86e48d appd[26]: endpoint_spot: error [DEBUG] - [2022-01-20 12:21:33,156] - amqpstorm.channel0 - Frame Received: Heartbeat
Jan 20 12:21:33 0f165c86e48d appd[26]: endpoint_ndf: error [DEBUG] - [2022-01-20 12:21:33,463] - amqpstorm.channel0 - Frame Sent: Heartbeat
Jan 20 12:21:33 0f165c86e48d appd[26]: endpoint_ndf: error [DEBUG] - [2022-01-20 12:21:33,467] - amqpstorm.channel0 - Frame Received: Heartbeat
Jan 20 12:22:33 0f165c86e48d appd[26]: endpoint_spot: error [DEBUG] - [2022-01-20 12:22:33,154] - amqpstorm.channel0 - Frame Sent: Heartbeat
Jan 20 12:22:33 0f165c86e48d appd[26]: endpoint_spot: error [DEBUG] - [2022-01-20 12:22:33,158] - amqpstorm.channel0 - Frame Received: Heartbeat
Jan 20 12:22:33 0f165c86e48d appd[26]: endpoint_ndf: error [DEBUG] - [2022-01-20 12:22:33,464] - amqpstorm.channel0 - Frame Sent: Heartbeat
Jan 20 12:22:33 0f165c86e48d appd[26]: endpoint_ndf: error [DEBUG] - [2022-01-20 12:22:33,469] - amqpstorm.channel0 - Frame Received: Heartbeat
Jan 20 12:23:33 0f165c86e48d appd[26]: endpoint_spot: error [DEBUG] - [2022-01-20 12:23:33,155] - amqpstorm.channel0 - Frame Sent: Heartbeat
Jan 20 12:23:33 0f165c86e48d appd[26]: endpoint_spot: error [DEBUG] - [2022-01-20 12:23:33,160] - amqpstorm.channel0 - Frame Received: Heartbeat
Jan 20 12:23:33 0f165c86e48d appd[26]: endpoint_ndf: error [DEBUG] - [2022-01-20 12:23:33,464] - amqpstorm.channel0 - Frame Sent: Heartbeat
Jan 20 12:23:33 0f165c86e48d appd[26]: endpoint_ndf: error [DEBUG] - [2022-01-20 12:23:33,471] - amqpstorm.channel0 - Frame Received: Heartbeat